package asketch.alloy.etc;

/**
 * This class defines some commonly used constants.
 */
public class Constants {

  public static final String SLASH = "/";
  public static final String UNDER_SCORE = "_";
  public static final String CROSS_PRODUCT = "->";

  public static final String NONE = "none";
  public static final String UNIV = "univ";
  public static final String IDEN = "iden";
  public static final String INT = "Int";
  public static final String SET = "set";
  public static final String SOME = "some";
  public static final String ONE = "one";
  public static final String LONE = "lone";
  public static final String ALL = "all";
  public static final String NO = "no";
  public static final String AND = "&&";
  public static final String OR = "||";
  public static final String IMPLIES = "=>";
  public static final String IFF = "<=>";
  public static final String EQ = "=";
  public static final String IN = "in";
  public static final String NEQ = "!=";
  public static final String NOT_IN = "!in";
  public static final String INTERSECT = "&";
  public static final String UNION = "+";
  public static final String DIFF = "-";
  public static final String TRANSPOSE = "~";
  public static final String REFLEXIVE_TRANSITIVE_CLOSURE = "*";
  public static final String TRANSITIVE_CLOSURE = "^";
  public static final String ORIGIN = "";
  public static final String NEGATE = "!";

  // Hole notations
  public static final String Q = "Q";
  public static final String LO = "LO";
  public static final String CO = "CO";
  public static final String UO = "UO";
  public static final String UOF = "UOF";
  public static final String UOE = "UOE";
  public static final String BO = "BO";
  public static final String E = "E";

  // Names of special signatures generated by ASketch
  public static final String ABSTRACT_Q = "Q";
  public static final String RESULT_Q = "_RQ_";
  public static final String ABSTRACT_LO = "LO";
  public static final String RESULT_LO = "_RLO_";
  public static final String ABSTRACT_CO = "CO";
  public static final String RESULT_CO = "_RCO_";
  public static final String ABSTRACT_UO = "UO";
  public static final String RESULT_UO = "_RUO_";
  public static final String ABSTRACT_UOF = "UOF";
  public static final String RESULT_UOF = "_RUOF_";
  public static final String ABSTRACT_UOE = "UOE";
  public static final String RESULT_UOE = "_RUOE_";
  public static final String ABSTRACT_BO = "BO";
  public static final String RESULT_BO = "_RBO_";
  public static final String ABSTRACT_E = "E";
  public static final String RESULT_E = "_RE_";
  public static final String Q_FUN_NAME = "q";
  public static final String UO_FUN_NAME = "uo";
  public static final String CO_FUN_NAME = "co";
  public static final String BO_FUN_NAME = "bo";
  public static final String UOE_FUN_NAME = "uoe";
  public static final String UOF_FUN_NAME = "uof";
  public static final String LO_FUN_NAME = "lo";
  public static final String EXPR_FUN_NAME = "expr";

  // Name of sketching command
  public static final String SKETCH_COMMAND_NAME = "Sketch";
}
